### PR TITLE
feat(user-object-sanitizer): added user object sanitizer

### PR DESCRIPTION
**Pull request by dotansimha**
First, we need to sanitize the User object, right before passing it to the client or external functions to avoid exposure of `services` array with the encrypted passwords.
Also, added to `options` the ability to provide another external sanitizer, so now the developer can filter fields before sending it to the client.

### CODE REVIEW

**Comment by pradel** [comment]
Nice but maybe it's better to use `pick` than `omit`?

**Comment by dotansimha** [comment]
@pradel, the internal uses `omit` because we just want to strip the `services` object.
The signature for the custom sanitizer is `(user, omitFunction)` so it will be easy to implement the method without any other dependencies. 
Maybe expose the `pick` as well, so the developers will be able to choose?

**Comment by pradel** [comment]
With the custom function you will be able tu use `pick` in your `omitFunction` so it's okay 😄

**Comment by dotansimha** [comment]
@pradel , also, I don't want to to use `pick` inside the internal sanitizer because then we might strip fields that aren't managed by `jsaccounts` from the user.

**Comment by pradel** [comment]
I was thinking in a meteor way only fields in profile should be accessible on client by default

**Comment by dotansimha** [comment]
Meteor exposes also the rest of the fields, not only the `profile` field. (am I wrong?)

**Comment by davidyaha** [comment]
I think the direction we are starting to head towards will leave the `profile` section of a user on a separate data store or even owned by the microservice it self.
IMO profile should not be mentioned in this package at all.

**Comment by davidyaha** [comment]
@TimMikeladze Are we good on this PR?

**Pull request merged**
