### PR TITLE
chore(flow): Added type declarations for accounts and made eslint and flow check happy

### PR DESCRIPTION
**Pull request by davidyaha**
Trying to accelerate and get some feedback on the flow typings. 
@TimMikeladze  I branched off from your flow branch. 
Hopefully everything was pushed and there is no merges.. anyhow, let me know if that's the case and I'll work on the necessary changes.

### CODE REVIEW

**Comment by TimMikeladze** [comment]
@davidyaha This looks solid, thanks for picking up where I left off.

**Comment by TimMikeladze** [comment]
@davidyaha Merge at your leisure.

**Comment by davidyaha** [comment]
Cool I would love to but I don't have write access to this package for some reason.

**Comment by TimMikeladze** [comment]
@davidyaha, the permisisons have been fixed, sorry about that. 

Merging this PR.

**Pull request merged**
