### PR TITLE
send impersonator user id field to db

### PR DESCRIPTION
**Pull request by stephschuster**

### CODE REVIEW

**Comment by dotansimha** [comment]
Looks good, but we need to add to the the DB interfaces as well :)

**Comment by stephschuster** [comment]
@dotansimha already added to Mongo project, exists other project that i need to update?

**Comment by stephschuster** [comment]
updated on redis: https://github.com/js-accounts/redis/pull/10
updated on mongo: https://github.com/js-accounts/mongo/pull/26

**Comment by Urigo** [comment]
@stephschuster !!!!   🥇

**Pull request merged**
